### ISSUE TITLE
Error when building docker container

### ISSUE THREAD

**Issue by saratrajput** [elephantrobotics/mycobot_ros#37]
I have the following error when building the docker container.

```
Building ros
Sending build context to Docker daemon  190.1MB
Step 1/16 : ARG BASE_IMAGE
Step 2/16 : FROM ${BASE_IMAGE}
18.04: Pulling from library/ubuntu
e4ca327ec0e7: Pull complete 
Digest: sha256:9bc830af2bef73276515a29aa896eedfa7bdf4bdbc5c1063b4c457a4bbb8cd79
Status: Downloaded newer image for ubuntu:18.04
 ---> 54919e10a95d
Step 3/16 : COPY --from=osrf/ros:melodic-desktop-full / /
melodic-desktop-full: Pulling from osrf/ros
4bbfd2c87b75: Pull complete 
d2e110be24e1: Pull complete 
889a7173dcfe: Pull complete 
1270d8e5a641: Pull complete 
6b8ca49cb51a: Pull complete 
c95c6800a35c: Pull complete 
47408d20bf58: Pull complete 
29f56ec2afd1: Pull complete 
a07d96849f4e: Pull complete 
86b45c5e6466: Pull complete 
d761800cb971: Pull complete 
8f3409eabec0: Pull complete 
aebe9f16eba2: Pull complete 
5c80026661cc: Pull complete 
d629bf3d1a44: Pull complete 
Digest: sha256:f9268872571969d1fa20a64d1a9225dd592451862b21c34d66e7b6be3541b8dd
Status: Downloaded newer image for osrf/ros:melodic-desktop-full
 ---> 457eabb12615
Step 4/16 : ENV BASH_ENV="/root/launch.sh"
 ---> Running in a2fba33a5c2a
Removing intermediate container a2fba33a5c2a
 ---> 400c387c6f8f
Step 5/16 : SHELL ["/bin/bash", "-c"]
 ---> Running in d478ec733dfb
Removing intermediate container d478ec733dfb
 ---> 1b56a0c4ae8d
Step 6/16 : ENTRYPOINT ["/bin/bash", "-c"]
 ---> Running in a599a61cbb3d
Removing intermediate container a599a61cbb3d
 ---> d4a0351a3d17
Step 7/16 : ARG ROS_DISTRO
 ---> Running in 57bc2b5de5cb
Removing intermediate container 57bc2b5de5cb
 ---> 6e04c0dc7082
Step 8/16 : RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> $BASH_ENV
 ---> Running in 1adec7b2084b
Removing intermediate container 1adec7b2084b
 ---> 5abb05b78021
Step 9/16 : WORKDIR /catkin_ws/src
 ---> Running in 67decfcc552b
Removing intermediate container 67decfcc552b
 ---> 4f4de8e20a54
Step 10/16 : COPY . mycobot_ros
 ---> 1d56f290fbfb
Step 11/16 : RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - &&     apt-get update &&     apt-get install -y         python-rosinstall         python-rosinstall-generator         python-wstool         build-essential         python-pip &&     rosdep install -r -y -i --from-paths . &&     rm -rf /var/lib/apt/lists/*
 ---> Running in ea7ef011be0e
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://packages.ros.org/ros/ubuntu bionic InRelease [4680 B]
Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:4 http://packages.ros.org/ros/ubuntu bionic/main amd64 Packages [772 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [26.7 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2320 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1428 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [560 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [593 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [34.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2755 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2202 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
Fetched 24.1 MB in 13s (1834 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.4ubuntu1).
python-rosinstall is already the newest version (0.7.8-1).
python-wstool is already the newest version (0.1.17-1).
python-wstool set to manually installed.
The following additional packages will be installed:
  dbus libpython-all-dev python-all python-all-dev python-crypto python-dbus
  python-gi python-keyring python-keyrings.alt python-pip-whl
  python-secretstorage python-wheel python-xdg
Suggested packages:
  default-dbus-session-bus | dbus-session-bus python-crypto-doc
  python-dbus-dbg python-dbus-doc python-gi-cairo gnome-keyring
  libkf5wallet-bin gir1.2-gnomekeyring-1.0 python-fs python-gdata
  python-keyczar python-secretstorage-doc
The following NEW packages will be installed:
  dbus libpython-all-dev python-all python-all-dev python-crypto python-dbus
  python-gi python-keyring python-keyrings.alt python-pip python-pip-whl
  python-rosinstall-generator python-secretstorage python-wheel python-xdg
0 upgraded, 15 newly installed, 0 to remove and 107 not upgraded.
Need to get 2626 kB of archives.
After this operation, 6315 kB of additional disk space will be used.
Get:1 http://packages.ros.org/ros/ubuntu bionic/main amd64 python-rosinstall-generator all 0.1.22-1 [11.5 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 dbus amd64 1.12.2-1ubuntu1.2 [150 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpython-all-dev amd64 2.7.15~rc1-1 [1092 B]
Get:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-all amd64 2.7.15~rc1-1 [1076 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-all-dev amd64 2.7.15~rc1-1 [1100 B]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-crypto amd64 2.6.1-8ubuntu2 [244 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-dbus amd64 1.2.6-1 [90.2 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python-gi amd64 3.26.1-2ubuntu1 [197 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-secretstorage all 2.3.1-2 [11.8 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-keyring all 10.6.0-1 [30.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-keyrings.alt all 3.0-1 [16.7 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python-pip-whl all 9.0.1-2.3~ubuntu1.18.04.5 [1653 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python-pip all 9.0.1-2.3~ubuntu1.18.04.5 [151 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python-wheel all 0.30.0-0.2 [36.4 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python-xdg all 0.25-4ubuntu1.1 [31.2 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2626 kB in 3s (844 kB/s)
Selecting previously unselected package dbus.
(Reading database ... 105310 files and directories currently installed.)
Preparing to unpack .../00-dbus_1.12.2-1ubuntu1.2_amd64.deb ...
Unpacking dbus (1.12.2-1ubuntu1.2) ...
Selecting previously unselected package libpython-all-dev:amd64.
Preparing to unpack .../01-libpython-all-dev_2.7.15~rc1-1_amd64.deb ...
Unpacking libpython-all-dev:amd64 (2.7.15~rc1-1) ...
Selecting previously unselected package python-all.
Preparing to unpack .../02-python-all_2.7.15~rc1-1_amd64.deb ...
Unpacking python-all (2.7.15~rc1-1) ...
Selecting previously unselected package python-all-dev.
Preparing to unpack .../03-python-all-dev_2.7.15~rc1-1_amd64.deb ...
Unpacking python-all-dev (2.7.15~rc1-1) ...
Selecting previously unselected package python-crypto.
Preparing to unpack .../04-python-crypto_2.6.1-8ubuntu2_amd64.deb ...
Unpacking python-crypto (2.6.1-8ubuntu2) ...
Selecting previously unselected package python-dbus.
Preparing to unpack .../05-python-dbus_1.2.6-1_amd64.deb ...
Unpacking python-dbus (1.2.6-1) ...
Selecting previously unselected package python-gi.
Preparing to unpack .../06-python-gi_3.26.1-2ubuntu1_amd64.deb ...
Unpacking python-gi (3.26.1-2ubuntu1) ...
Selecting previously unselected package python-secretstorage.
Preparing to unpack .../07-python-secretstorage_2.3.1-2_all.deb ...
Unpacking python-secretstorage (2.3.1-2) ...
Selecting previously unselected package python-keyring.
Preparing to unpack .../08-python-keyring_10.6.0-1_all.deb ...
Unpacking python-keyring (10.6.0-1) ...
Selecting previously unselected package python-keyrings.alt.
Preparing to unpack .../09-python-keyrings.alt_3.0-1_all.deb ...
Unpacking python-keyrings.alt (3.0-1) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../10-python-pip-whl_9.0.1-2.3~ubuntu1.18.04.5_all.deb ...
Unpacking python-pip-whl (9.0.1-2.3~ubuntu1.18.04.5) ...
Selecting previously unselected package python-pip.
Preparing to unpack .../11-python-pip_9.0.1-2.3~ubuntu1.18.04.5_all.deb ...
Unpacking python-pip (9.0.1-2.3~ubuntu1.18.04.5) ...
Selecting previously unselected package python-rosinstall-generator.
Preparing to unpack .../12-python-rosinstall-generator_0.1.22-1_all.deb ...
Unpacking python-rosinstall-generator (0.1.22-1) ...
Selecting previously unselected package python-wheel.
Preparing to unpack .../13-python-wheel_0.30.0-0.2_all.deb ...
Unpacking python-wheel (0.30.0-0.2) ...
Selecting previously unselected package python-xdg.
Preparing to unpack .../14-python-xdg_0.25-4ubuntu1.1_all.deb ...
Unpacking python-xdg (0.25-4ubuntu1.1) ...
Setting up python-pip-whl (9.0.1-2.3~ubuntu1.18.04.5) ...
Setting up python-crypto (2.6.1-8ubuntu2) ...
Setting up python-wheel (0.30.0-0.2) ...
Setting up libpython-all-dev:amd64 (2.7.15~rc1-1) ...
Setting up python-keyrings.alt (3.0-1) ...
Setting up python-gi (3.26.1-2ubuntu1) ...
Setting up dbus (1.12.2-1ubuntu1.2) ...
Setting up python-dbus (1.2.6-1) ...
Setting up python-pip (9.0.1-2.3~ubuntu1.18.04.5) ...
Setting up python-all (2.7.15~rc1-1) ...
Setting up python-rosinstall-generator (0.1.22-1) ...
Setting up python-xdg (0.25-4ubuntu1.1) ...
Setting up python-secretstorage (2.3.1-2) ...
Setting up python-keyring (10.6.0-1) ...
Setting up python-all-dev (2.7.15~rc1-1) ...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libfcl-dev libfcl0.5 liboctomap-dev liboctomap1.8
  ros-melodic-eigen-stl-containers ros-melodic-geometric-shapes
  ros-melodic-moveit-core ros-melodic-moveit-msgs
  ros-melodic-moveit-ros-occupancy-map-monitor ros-melodic-moveit-ros-planning
  ros-melodic-object-recognition-msgs ros-melodic-octomap
  ros-melodic-octomap-msgs ros-melodic-pybind11-catkin
  ros-melodic-random-numbers ros-melodic-srdfdom
The following NEW packages will be installed:
  libfcl-dev libfcl0.5 liboctomap-dev liboctomap1.8
  ros-melodic-eigen-stl-containers ros-melodic-geometric-shapes
  ros-melodic-moveit-core ros-melodic-moveit-fake-controller-manager
  ros-melodic-moveit-msgs ros-melodic-moveit-ros-occupancy-map-monitor
  ros-melodic-moveit-ros-planning ros-melodic-object-recognition-msgs
  ros-melodic-octomap ros-melodic-octomap-msgs ros-melodic-pybind11-catkin
  ros-melodic-random-numbers ros-melodic-srdfdom
0 upgraded, 17 newly installed, 0 to remove and 107 not upgraded.
Need to get 4610 kB of archives.
After this operation, 49.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libfcl0.5 amd64 0.5.0-5 [902 kB]
Get:2 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-eigen-stl-containers amd64 0.1.8-0bionic.20201015.033045 [6816 B]
Get:3 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-octomap amd64 1.9.7-1bionic.20210504.141732 [191 kB]
Get:4 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-random-numbers amd64 0.3.2-0bionic.20201015.065429 [28.0 kB]
Get:5 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-geometric-shapes amd64 0.6.4-1bionic.20210519.200253 [80.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/universe amd64 liboctomap1.8 amd64 1.8.1+dfsg-1 [72.5 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 liboctomap-dev amd64 1.8.1+dfsg-1 [119 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libfcl-dev amd64 0.5.0-5 [88.6 kB]
Get:9 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-object-recognition-msgs amd64 0.4.1-0bionic.20210505.043500 [70.1 kB]
Get:10 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-octomap-msgs amd64 0.3.5-1bionic.20210505.011716 [29.4 kB]
Get:11 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-msgs amd64 0.10.1-1bionic.20210505.043840 [664 kB]
Get:12 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-pybind11-catkin amd64 2.4.3-1bionic.20200731.225101 [118 kB]
Get:13 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-srdfdom amd64 0.5.2-1bionic.20210505.022841 [60.5 kB]
Get:14 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-core amd64 1.0.8-1bionic.20210719.224614 [1192 kB]
Get:15 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-occupancy-map-monitor amd64 1.0.8-1bionic.20210719.231211 [135 kB]
Get:16 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-planning amd64 1.0.8-1bionic.20210719.231635 [787 kB]
Get:17 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-fake-controller-manager amd64 1.0.8-1bionic.20210719.233337 [66.4 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 4610 kB in 24s (195 kB/s)
Selecting previously unselected package libfcl0.5.
(Reading database ... 105876 files and directories currently installed.)
Preparing to unpack .../00-libfcl0.5_0.5.0-5_amd64.deb ...
Unpacking libfcl0.5 (0.5.0-5) ...
Selecting previously unselected package liboctomap1.8.
Preparing to unpack .../01-liboctomap1.8_1.8.1+dfsg-1_amd64.deb ...
Unpacking liboctomap1.8 (1.8.1+dfsg-1) ...
Selecting previously unselected package liboctomap-dev.
Preparing to unpack .../02-liboctomap-dev_1.8.1+dfsg-1_amd64.deb ...
Unpacking liboctomap-dev (1.8.1+dfsg-1) ...
Selecting previously unselected package ros-melodic-eigen-stl-containers.
Preparing to unpack .../03-ros-melodic-eigen-stl-containers_0.1.8-0bionic.20201015.033045_amd64.deb ...
Unpacking ros-melodic-eigen-stl-containers (0.1.8-0bionic.20201015.033045) ...
Selecting previously unselected package ros-melodic-octomap.
Preparing to unpack .../04-ros-melodic-octomap_1.9.7-1bionic.20210504.141732_amd64.deb ...
Unpacking ros-melodic-octomap (1.9.7-1bionic.20210504.141732) ...
Selecting previously unselected package ros-melodic-random-numbers.
Preparing to unpack .../05-ros-melodic-random-numbers_0.3.2-0bionic.20201015.065429_amd64.deb ...
Unpacking ros-melodic-random-numbers (0.3.2-0bionic.20201015.065429) ...
Selecting previously unselected package ros-melodic-geometric-shapes.
Preparing to unpack .../06-ros-melodic-geometric-shapes_0.6.4-1bionic.20210519.200253_amd64.deb ...
Unpacking ros-melodic-geometric-shapes (0.6.4-1bionic.20210519.200253) ...
Selecting previously unselected package libfcl-dev.
Preparing to unpack .../07-libfcl-dev_0.5.0-5_amd64.deb ...
Unpacking libfcl-dev (0.5.0-5) ...
Selecting previously unselected package ros-melodic-object-recognition-msgs.
Preparing to unpack .../08-ros-melodic-object-recognition-msgs_0.4.1-0bionic.20210505.043500_amd64.deb ...
Unpacking ros-melodic-object-recognition-msgs (0.4.1-0bionic.20210505.043500) ...
Selecting previously unselected package ros-melodic-octomap-msgs.
Preparing to unpack .../09-ros-melodic-octomap-msgs_0.3.5-1bionic.20210505.011716_amd64.deb ...
Unpacking ros-melodic-octomap-msgs (0.3.5-1bionic.20210505.011716) ...
Selecting previously unselected package ros-melodic-moveit-msgs.
Preparing to unpack .../10-ros-melodic-moveit-msgs_0.10.1-1bionic.20210505.043840_amd64.deb ...
Unpacking ros-melodic-moveit-msgs (0.10.1-1bionic.20210505.043840) ...
Selecting previously unselected package ros-melodic-pybind11-catkin.
Preparing to unpack .../11-ros-melodic-pybind11-catkin_2.4.3-1bionic.20200731.225101_amd64.deb ...
Unpacking ros-melodic-pybind11-catkin (2.4.3-1bionic.20200731.225101) ...
Selecting previously unselected package ros-melodic-srdfdom.
Preparing to unpack .../12-ros-melodic-srdfdom_0.5.2-1bionic.20210505.022841_amd64.deb ...
Unpacking ros-melodic-srdfdom (0.5.2-1bionic.20210505.022841) ...
Selecting previously unselected package ros-melodic-moveit-core.
Preparing to unpack .../13-ros-melodic-moveit-core_1.0.8-1bionic.20210719.224614_amd64.deb ...
Unpacking ros-melodic-moveit-core (1.0.8-1bionic.20210719.224614) ...
Selecting previously unselected package ros-melodic-moveit-ros-occupancy-map-monitor.
Preparing to unpack .../14-ros-melodic-moveit-ros-occupancy-map-monitor_1.0.8-1bionic.20210719.231211_amd64.deb ...
Unpacking ros-melodic-moveit-ros-occupancy-map-monitor (1.0.8-1bionic.20210719.231211) ...
Selecting previously unselected package ros-melodic-moveit-ros-planning.
Preparing to unpack .../15-ros-melodic-moveit-ros-planning_1.0.8-1bionic.20210719.231635_amd64.deb ...
Unpacking ros-melodic-moveit-ros-planning (1.0.8-1bionic.20210719.231635) ...
Selecting previously unselected package ros-melodic-moveit-fake-controller-manager.
Preparing to unpack .../16-ros-melodic-moveit-fake-controller-manager_1.0.8-1bionic.20210719.233337_amd64.deb ...
Unpacking ros-melodic-moveit-fake-controller-manager (1.0.8-1bionic.20210719.233337) ...
Setting up ros-melodic-octomap (1.9.7-1bionic.20210504.141732) ...
Setting up ros-melodic-random-numbers (0.3.2-0bionic.20201015.065429) ...
Setting up ros-melodic-eigen-stl-containers (0.1.8-0bionic.20201015.033045) ...
Setting up ros-melodic-srdfdom (0.5.2-1bionic.20210505.022841) ...
Setting up ros-melodic-octomap-msgs (0.3.5-1bionic.20210505.011716) ...
Setting up ros-melodic-pybind11-catkin (2.4.3-1bionic.20200731.225101) ...
Setting up ros-melodic-object-recognition-msgs (0.4.1-0bionic.20210505.043500) ...
Setting up liboctomap1.8 (1.8.1+dfsg-1) ...
Setting up libfcl0.5 (0.5.0-5) ...
Setting up ros-melodic-geometric-shapes (0.6.4-1bionic.20210519.200253) ...
Setting up ros-melodic-moveit-msgs (0.10.1-1bionic.20210505.043840) ...
Setting up liboctomap-dev (1.8.1+dfsg-1) ...
Setting up libfcl-dev (0.5.0-5) ...
Setting up ros-melodic-moveit-core (1.0.8-1bionic.20210719.224614) ...
Setting up ros-melodic-moveit-ros-occupancy-map-monitor (1.0.8-1bionic.20210719.231211) ...
Setting up ros-melodic-moveit-ros-planning (1.0.8-1bionic.20210719.231635) ...
Setting up ros-melodic-moveit-fake-controller-manager (1.0.8-1bionic.20210719.233337) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  liburdfdom-tools python-bs4 python-chardet python-html5lib python-lxml
  python-webencodings
Suggested packages:
  python-genshi python-lxml-dbg python-lxml-doc
The following NEW packages will be installed:
  liburdfdom-tools python-bs4 python-chardet python-html5lib python-lxml
  python-webencodings ros-melodic-moveit-kinematics
0 upgraded, 7 newly installed, 0 to remove and 107 not upgraded.
Need to get 1400 kB of archives.
After this operation, 7774 kB of additional disk space will be used.
Get:1 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-kinematics amd64 1.0.8-1bionic.20210719.232855 [248 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-bs4 all 4.6.0-1 [67.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-chardet all 3.0.4-1 [80.3 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-webencodings all 0.5-2 [10.3 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-html5lib all 0.999999999-1 [83.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python-lxml amd64 4.2.1-1ubuntu0.4 [897 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 liburdfdom-tools amd64 1.0.0-2ubuntu0.1 [12.5 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1400 kB in 2s (623 kB/s)
Selecting previously unselected package python-bs4.
(Reading database ... 107628 files and directories currently installed.)
Preparing to unpack .../0-python-bs4_4.6.0-1_all.deb ...
Unpacking python-bs4 (4.6.0-1) ...
Selecting previously unselected package python-chardet.
Preparing to unpack .../1-python-chardet_3.0.4-1_all.deb ...
Unpacking python-chardet (3.0.4-1) ...
Selecting previously unselected package python-webencodings.
Preparing to unpack .../2-python-webencodings_0.5-2_all.deb ...
Unpacking python-webencodings (0.5-2) ...
Selecting previously unselected package python-html5lib.
Preparing to unpack .../3-python-html5lib_0.999999999-1_all.deb ...
Unpacking python-html5lib (0.999999999-1) ...
Selecting previously unselected package python-lxml:amd64.
Preparing to unpack .../4-python-lxml_4.2.1-1ubuntu0.4_amd64.deb ...
Unpacking python-lxml:amd64 (4.2.1-1ubuntu0.4) ...
Selecting previously unselected package liburdfdom-tools.
Preparing to unpack .../5-liburdfdom-tools_1.0.0-2ubuntu0.1_amd64.deb ...
Unpacking liburdfdom-tools (1.0.0-2ubuntu0.1) ...
Selecting previously unselected package ros-melodic-moveit-kinematics.
Preparing to unpack .../6-ros-melodic-moveit-kinematics_1.0.8-1bionic.20210719.232855_amd64.deb ...
Unpacking ros-melodic-moveit-kinematics (1.0.8-1bionic.20210719.232855) ...
Setting up liburdfdom-tools (1.0.0-2ubuntu0.1) ...
Setting up python-chardet (3.0.4-1) ...
Setting up python-bs4 (4.6.0-1) ...
Setting up python-lxml:amd64 (4.2.1-1ubuntu0.4) ...
Setting up python-webencodings (0.5-2) ...
Setting up ros-melodic-moveit-kinematics (1.0.8-1bionic.20210719.232855) ...
Setting up python-html5lib (0.999999999-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libglew-dev libglew2.0 libomp-dev libomp5 ros-melodic-eigenpy
  ros-melodic-moveit-ros-manipulation ros-melodic-moveit-ros-move-group
  ros-melodic-moveit-ros-perception ros-melodic-moveit-ros-planning-interface
  ros-melodic-moveit-ros-robot-interaction
  ros-melodic-moveit-ros-visualization ros-melodic-moveit-ros-warehouse
  ros-melodic-warehouse-ros
Suggested packages:
  glew-utils libomp-doc
The following NEW packages will be installed:
  libglew-dev libglew2.0 libomp-dev libomp5 ros-melodic-eigenpy
  ros-melodic-moveit-ros-manipulation ros-melodic-moveit-ros-move-group
  ros-melodic-moveit-ros-perception ros-melodic-moveit-ros-planning-interface
  ros-melodic-moveit-ros-robot-interaction
  ros-melodic-moveit-ros-visualization ros-melodic-moveit-ros-warehouse
  ros-melodic-moveit-setup-assistant ros-melodic-warehouse-ros
0 upgraded, 14 newly installed, 0 to remove and 107 not upgraded.
Need to get 4912 kB of archives.
After this operation, 25.6 MB of additional disk space will be used.
Get:1 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-eigenpy amd64 2.6.4-1bionic.20210527.213718 [1009 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libglew2.0 amd64 2.0.0-5 [140 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libglew-dev amd64 2.0.0-5 [120 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp5 amd64 5.0.1-1 [234 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libomp-dev amd64 5.0.1-1 [5088 B]
Get:6 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-move-group amd64 1.0.8-1bionic.20210719.233440 [344 kB]
Get:7 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-manipulation amd64 1.0.8-1bionic.20210719.234512 [299 kB]
Get:8 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-perception amd64 1.0.8-1bionic.20210719.233424 [274 kB]
Get:9 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-warehouse-ros amd64 0.9.4-1bionic.20210505.034027 [90.2 kB]
Get:10 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-warehouse amd64 1.0.8-1bionic.20210719.233518 [349 kB]
Get:11 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-planning-interface amd64 1.0.8-1bionic.20210719.235155 [527 kB]
Get:12 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-robot-interaction amd64 1.0.8-1bionic.20210719.233456 [125 kB]
Get:13 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-ros-visualization amd64 1.0.8-1bionic.20210720.000350 [546 kB]
Get:14 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-setup-assistant amd64 1.0.8-1bionic.20210720.001858 [850 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 4912 kB in 19s (264 kB/s)
Selecting previously unselected package libglew2.0:amd64.
(Reading database ... 107913 files and directories currently installed.)
Preparing to unpack .../00-libglew2.0_2.0.0-5_amd64.deb ...
Unpacking libglew2.0:amd64 (2.0.0-5) ...
Selecting previously unselected package libglew-dev:amd64.
Preparing to unpack .../01-libglew-dev_2.0.0-5_amd64.deb ...
Unpacking libglew-dev:amd64 (2.0.0-5) ...
Selecting previously unselected package ros-melodic-eigenpy.
Preparing to unpack .../02-ros-melodic-eigenpy_2.6.4-1bionic.20210527.213718_amd64.deb ...
Unpacking ros-melodic-eigenpy (2.6.4-1bionic.20210527.213718) ...
Selecting previously unselected package ros-melodic-moveit-ros-move-group.
Preparing to unpack .../03-ros-melodic-moveit-ros-move-group_1.0.8-1bionic.20210719.233440_amd64.deb ...
Unpacking ros-melodic-moveit-ros-move-group (1.0.8-1bionic.20210719.233440) ...
Selecting previously unselected package ros-melodic-moveit-ros-manipulation.
Preparing to unpack .../04-ros-melodic-moveit-ros-manipulation_1.0.8-1bionic.20210719.234512_amd64.deb ...
Unpacking ros-melodic-moveit-ros-manipulation (1.0.8-1bionic.20210719.234512) ...
Selecting previously unselected package libomp5:amd64.
Preparing to unpack .../05-libomp5_5.0.1-1_amd64.deb ...
Unpacking libomp5:amd64 (5.0.1-1) ...
Selecting previously unselected package libomp-dev.
Preparing to unpack .../06-libomp-dev_5.0.1-1_amd64.deb ...
Unpacking libomp-dev (5.0.1-1) ...
Selecting previously unselected package ros-melodic-moveit-ros-perception.
Preparing to unpack .../07-ros-melodic-moveit-ros-perception_1.0.8-1bionic.20210719.233424_amd64.deb ...
Unpacking ros-melodic-moveit-ros-perception (1.0.8-1bionic.20210719.233424) ...
Selecting previously unselected package ros-melodic-warehouse-ros.
Preparing to unpack .../08-ros-melodic-warehouse-ros_0.9.4-1bionic.20210505.034027_amd64.deb ...
Unpacking ros-melodic-warehouse-ros (0.9.4-1bionic.20210505.034027) ...
Selecting previously unselected package ros-melodic-moveit-ros-warehouse.
Preparing to unpack .../09-ros-melodic-moveit-ros-warehouse_1.0.8-1bionic.20210719.233518_amd64.deb ...
Unpacking ros-melodic-moveit-ros-warehouse (1.0.8-1bionic.20210719.233518) ...
Selecting previously unselected package ros-melodic-moveit-ros-planning-interface.
Preparing to unpack .../10-ros-melodic-moveit-ros-planning-interface_1.0.8-1bionic.20210719.235155_amd64.deb ...
Unpacking ros-melodic-moveit-ros-planning-interface (1.0.8-1bionic.20210719.235155) ...
Selecting previously unselected package ros-melodic-moveit-ros-robot-interaction.
Preparing to unpack .../11-ros-melodic-moveit-ros-robot-interaction_1.0.8-1bionic.20210719.233456_amd64.deb ...
Unpacking ros-melodic-moveit-ros-robot-interaction (1.0.8-1bionic.20210719.233456) ...
Selecting previously unselected package ros-melodic-moveit-ros-visualization.
Preparing to unpack .../12-ros-melodic-moveit-ros-visualization_1.0.8-1bionic.20210720.000350_amd64.deb ...
Unpacking ros-melodic-moveit-ros-visualization (1.0.8-1bionic.20210720.000350) ...
Selecting previously unselected package ros-melodic-moveit-setup-assistant.
Preparing to unpack .../13-ros-melodic-moveit-setup-assistant_1.0.8-1bionic.20210720.001858_amd64.deb ...
Unpacking ros-melodic-moveit-setup-assistant (1.0.8-1bionic.20210720.001858) ...
Setting up ros-melodic-warehouse-ros (0.9.4-1bionic.20210505.034027) ...
Setting up ros-melodic-eigenpy (2.6.4-1bionic.20210527.213718) ...
Setting up libomp5:amd64 (5.0.1-1) ...
Setting up ros-melodic-moveit-ros-move-group (1.0.8-1bionic.20210719.233440) ...
Setting up ros-melodic-moveit-ros-robot-interaction (1.0.8-1bionic.20210719.233456) ...
Setting up libomp-dev (5.0.1-1) ...
Setting up libglew2.0:amd64 (2.0.0-5) ...
Setting up libglew-dev:amd64 (2.0.0-5) ...
Setting up ros-melodic-moveit-ros-warehouse (1.0.8-1bionic.20210719.233518) ...
Setting up ros-melodic-moveit-ros-manipulation (1.0.8-1bionic.20210719.234512) ...
Setting up ros-melodic-moveit-ros-perception (1.0.8-1bionic.20210719.233424) ...
Setting up ros-melodic-moveit-ros-planning-interface (1.0.8-1bionic.20210719.235155) ...
Setting up ros-melodic-moveit-ros-visualization (1.0.8-1bionic.20210720.000350) ...
Setting up ros-melodic-moveit-setup-assistant (1.0.8-1bionic.20210720.001858) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  ros-melodic-joint-state-publisher-gui
0 upgraded, 1 newly installed, 0 to remove and 107 not upgraded.
Need to get 12.0 kB of archives.
After this operation, 55.3 kB of additional disk space will be used.
Get:1 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-joint-state-publisher-gui amd64 1.12.15-1bionic.20210716.091334 [12.0 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 12.0 kB in 1s (16.9 kB/s)
Selecting previously unselected package ros-melodic-joint-state-publisher-gui.
(Reading database ... 108543 files and directories currently installed.)
Preparing to unpack .../ros-melodic-joint-state-publisher-gui_1.12.15-1bionic.20210716.091334_amd64.deb ...
Unpacking ros-melodic-joint-state-publisher-gui (1.12.15-1bionic.20210716.091334) ...
Setting up ros-melodic-joint-state-publisher-gui (1.12.15-1bionic.20210716.091334) ...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  blt tk8.6-blt2.5
Suggested packages:
  blt-demo tix python-tk-dbg
The following NEW packages will be installed:
  blt python-tk tk8.6-blt2.5
0 upgraded, 3 newly installed, 0 to remove and 107 not upgraded.
Need to get 603 kB of archives.
After this operation, 2122 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 tk8.6-blt2.5 amd64 2.5.3+dfsg-4 [572 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 blt amd64 2.5.3+dfsg-4 [4944 B]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 python-tk amd64 2.7.17-1~18.04 [26.0 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 603 kB in 2s (259 kB/s)
Selecting previously unselected package tk8.6-blt2.5.
(Reading database ... 108557 files and directories currently installed.)
Preparing to unpack .../tk8.6-blt2.5_2.5.3+dfsg-4_amd64.deb ...
Unpacking tk8.6-blt2.5 (2.5.3+dfsg-4) ...
Selecting previously unselected package blt.
Preparing to unpack .../blt_2.5.3+dfsg-4_amd64.deb ...
Unpacking blt (2.5.3+dfsg-4) ...
Selecting previously unselected package python-tk.
Preparing to unpack .../python-tk_2.7.17-1~18.04_amd64.deb ...
Unpacking python-tk (2.7.17-1~18.04) ...
Setting up tk8.6-blt2.5 (2.5.3+dfsg-4) ...
Setting up blt (2.5.3+dfsg-4) ...
Setting up python-tk (2.7.17-1~18.04) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  evemu-tools evtest inputattach joystick libevemu3 libsdl1.2debian
The following NEW packages will be installed:
  evemu-tools evtest inputattach joystick libevemu3 libsdl1.2debian
  ros-melodic-joy
0 upgraded, 7 newly installed, 0 to remove and 107 not upgraded.
Need to get 337 kB of archives.
After this operation, 1145 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libevemu3 amd64 2.6.0-0.1 [12.2 kB]
Get:2 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-joy amd64 1.14.0-1bionic.20210505.032331 [53.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/universe amd64 evemu-tools amd64 2.6.0-0.1 [12.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libsdl1.2debian amd64 1.2.15+dfsg2-0.1ubuntu0.1 [175 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe amd64 joystick amd64 1:1.6.0-2 [45.9 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/universe amd64 evtest amd64 1:1.33-1build1 [15.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 inputattach amd64 1:1.6.0-2 [21.5 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 337 kB in 1s (225 kB/s)
Selecting previously unselected package libevemu3:amd64.
(Reading database ... 108590 files and directories currently installed.)
Preparing to unpack .../0-libevemu3_2.6.0-0.1_amd64.deb ...
Unpacking libevemu3:amd64 (2.6.0-0.1) ...
Selecting previously unselected package evemu-tools.
Preparing to unpack .../1-evemu-tools_2.6.0-0.1_amd64.deb ...
Unpacking evemu-tools (2.6.0-0.1) ...
Selecting previously unselected package libsdl1.2debian:amd64.
Preparing to unpack .../2-libsdl1.2debian_1.2.15+dfsg2-0.1ubuntu0.1_amd64.deb ...
Unpacking libsdl1.2debian:amd64 (1.2.15+dfsg2-0.1ubuntu0.1) ...
Selecting previously unselected package joystick.
Preparing to unpack .../3-joystick_1%3a1.6.0-2_amd64.deb ...
Unpacking joystick (1:1.6.0-2) ...
Selecting previously unselected package ros-melodic-joy.
Preparing to unpack .../4-ros-melodic-joy_1.14.0-1bionic.20210505.032331_amd64.deb ...
Unpacking ros-melodic-joy (1.14.0-1bionic.20210505.032331) ...
Selecting previously unselected package evtest.
Preparing to unpack .../5-evtest_1%3a1.33-1build1_amd64.deb ...
Unpacking evtest (1:1.33-1build1) ...
Selecting previously unselected package inputattach.
Preparing to unpack .../6-inputattach_1%3a1.6.0-2_amd64.deb ...
Unpacking inputattach (1:1.6.0-2) ...
Setting up inputattach (1:1.6.0-2) ...
Setting up libsdl1.2debian:amd64 (1.2.15+dfsg2-0.1ubuntu0.1) ...
Setting up evtest (1:1.33-1build1) ...
Setting up libevemu3:amd64 (2.6.0-0.1) ...
Setting up evemu-tools (2.6.0-0.1) ...
Setting up joystick (1:1.6.0-2) ...
Setting up ros-melodic-joy (1.14.0-1bionic.20210505.032331) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Reading package lists...
Building dependency tree...
Reading state information...
ros-melodic-moveit-msgs is already the newest version (0.10.1-1bionic.20210505.043840).
ros-melodic-moveit-msgs set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 107 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  ros-melodic-ompl
The following NEW packages will be installed:
  ros-melodic-moveit-planners-ompl ros-melodic-ompl
0 upgraded, 2 newly installed, 0 to remove and 107 not upgraded.
Need to get 1888 kB of archives.
After this operation, 10.5 MB of additional disk space will be used.
Get:1 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-ompl amd64 1.4.2-5bionic.20191212.045602 [1527 kB]
Get:2 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-moveit-planners-ompl amd64 1.0.8-1bionic.20210719.233345 [361 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1888 kB in 14s (137 kB/s)
Selecting previously unselected package ros-melodic-ompl.
(Reading database ... 108685 files and directories currently installed.)
Preparing to unpack .../ros-melodic-ompl_1.4.2-5bionic.20191212.045602_amd64.deb ...
Unpacking ros-melodic-ompl (1.4.2-5bionic.20191212.045602) ...
Selecting previously unselected package ros-melodic-moveit-planners-ompl.
Preparing to unpack .../ros-melodic-moveit-planners-ompl_1.0.8-1bionic.20210719.233345_amd64.deb ...
Unpacking ros-melodic-moveit-planners-ompl (1.0.8-1bionic.20210719.233345) ...
Setting up ros-melodic-ompl (1.4.2-5bionic.20191212.045602) ...
Setting up ros-melodic-moveit-planners-ompl (1.0.8-1bionic.20210719.233345) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Reading package lists...
Building dependency tree...
Reading state information...
ros-melodic-moveit-ros-move-group is already the newest version (1.0.8-1bionic.20210719.233440).
ros-melodic-moveit-ros-move-group set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 107 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
ros-melodic-moveit-ros-visualization is already the newest version (1.0.8-1bionic.20210720.000350).
ros-melodic-moveit-ros-visualization set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 107 not upgraded.
executing command [apt-get install -y ros-melodic-moveit-fake-controller-manager]
executing command [apt-get install -y ros-melodic-moveit-kinematics]
executing command [apt-get install -y ros-melodic-moveit-setup-assistant]
executing command [apt-get install -y ros-melodic-joint-state-publisher-gui]
executing command [apt-get install -y python-tk]
executing command [apt-get install -y ros-melodic-joy]
executing command [apt-get install -y ros-melodic-moveit-msgs]
executing command [apt-get install -y ros-melodic-moveit-planners-ompl]
executing command [apt-get install -y ros-melodic-moveit-ros-move-group]
executing command [apt-get install -y ros-melodic-moveit-ros-visualization]
#All required rosdeps installed successfully
Removing intermediate container ea7ef011be0e
 ---> ebc79e332092
Step 12/16 : ARG PYMYCOBOT_VERSION
 ---> Running in cea6ee5459b7
Removing intermediate container cea6ee5459b7
 ---> d29a06c5bb6b
Step 13/16 : RUN pip install "pymycobot $PYMYCOBOT_VERSION" --user
 ---> Running in d38a7a7eb23a
Collecting pymycobot>=2<3
  Downloading https://files.pythonhosted.org/packages/f6/2e/766270044b6ec965e4fc37e908578497b402452cd94f755e87c8686e1263/pymycobot-2.6.0b1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6DbU8C/pymycobot/setup.py", line 12, in <module>
        import pymycobot
      File "pymycobot/__init__.py", line 9, in <module>
        from pymycobot import utils
      File "pymycobot/utils.py", line 7, in <module>
        except ModuleNotFoundError:
    NameError: name 'ModuleNotFoundError' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6DbU8C/pymycobot/
The command '/bin/bash -c pip install "pymycobot $PYMYCOBOT_VERSION" --user' returned a non-zero code: 1
ERROR: Service 'ros' failed to build : Build failed
```

**Comment by abrahamperz** [comment]
Same issue, at same **13**th **step**

**Comment by apockill** [comment]
Maybe we should pin the `pymycobot` version in the docker container? :thinking:

**Comment by abrahamperz** [comment]
@apockill could be, I am using Ubuntu 18.04 LTS
Also if you want to share the dockerfile I can help you with the debugging

**Comment by apockill** [comment]
I've created a PR that should fix the issue https://github.com/elephantrobotics/mycobot_ros/pull/39/files

I think we might want to add some CI to the repo that tests the builds complete.

**Comment by abrahamperz** [comment]
@apockill the error stills  in the docker image
Step 1/16 : ARG BASE_IMAGE
Step 2/16 : FROM ${BASE_IMAGE}
 ---> 4f4bf5e1fe4b
Step 3/16 : COPY --from=osrf/ros:melodic-desktop-full / /
 ---> Using cache
 ---> cb685401d019
Step 4/16 : ENV BASH_ENV="/root/launch.sh"
 ---> Using cache
 ---> b2bbecebf2db
Step 5/16 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> bd921b40ad6f
Step 6/16 : ENTRYPOINT ["/bin/bash", "-c"]
 ---> Using cache
 ---> 6610e64dae57
Step 7/16 : ARG ROS_DISTRO
 ---> Using cache
 ---> 0c29316b2a5e
Step 8/16 : RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> $BASH_ENV
 ---> Using cache
 ---> 799171fcaf54
Step 9/16 : WORKDIR /catkin_ws/src
 ---> Using cache
 ---> f7842b054bdc
Step 10/16 : COPY . mycobot_ros
 ---> c04de159f91c
Step 11/16 : RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - &&     apt-get update &&     apt-get install -y         python-rosinstall         python-rosinstall-generator         python-wstool         build-essential         python-pip3 &&     rosdep install -r -y -i --from-paths . &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 35cf8a2aa84c
[91mWarning: apt-key output should not be parsed (stdout is not a terminal)
[0mOK
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://packages.ros.org/ros/ubuntu bionic InRelease [4680 B]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1428 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [26.7 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/multiverse i386 Packages [7114 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [567 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/restricted i386 Packages [26.7 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [1296 kB]
Get:10 http://packages.ros.org/ros/ubuntu bionic/main amd64 Packages [772 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [1238 kB]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2326 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/multiverse i386 Packages [177 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:18 http://packages.ros.org/ros/ubuntu bionic/main i386 Packages [26.3 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic/restricted i386 Packages [13.5 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:22 http://archive.ubuntu.com/ubuntu bionic/main i386 Packages [1328 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic/universe i386 Packages [11.3 MB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2202 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [1688 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/restricted i386 Packages [37.2 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [600 kB]
Get:28 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse i386 Packages [13.1 kB]
Get:29 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [34.4 kB]
Get:30 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [1985 kB]
Get:31 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2761 kB]
Get:32 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
Get:33 http://archive.ubuntu.com/ubuntu bionic-backports/universe i386 Packages [11.4 kB]
Get:34 http://archive.ubuntu.com/ubuntu bionic-backports/main i386 Packages [11.2 kB]
Get:35 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
Fetched 43.3 MB in 4s (10.4 MB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
[91mE: Unable to locate package python-pip3
[0m

**Comment by apockill** [comment]
How are you running the build?

**Comment by apockill** [comment]
![typo](https://user-images.githubusercontent.com/1740412/134219388-eda526ab-0ef8-49c2-9bcc-1838ba98c9cc.png)
@abrahamperz it appears you didn't check out my PR, and typed it yourself. The package name is `python3-pip` not `python-pip3`
